// const this.#ServiceManagerManager = require('../app/service_manager');
// /**
//  * @type this.#ServiceManagerManager this.#ServiceManager
//  */
// let this.#ServiceManager;
// -- 以上代码仅为了方便编写脚本命令（取消注释可以使用this.#ServiceManager及链式调用的代码提示，再运行前需要注释掉，否则会导致无法正常运行 --

[
    { Cmd: 'role.getMyRoleInfo', Params: {}, Describe: '获取当前玩家信息', Immediate: true },
    { Cmd: "roleBuilding.createBuild", Params: { "BuildingID": 2, "SerialNum": 0, "Pos": 0 }, Describe: '建造仓库', Immediate: true, IsInvalid: this.#ServiceManager.roleBuilding.CheckContainsBuilding.bind(this.#ServiceManager.roleBuilding, 2), Handler: [this.#ServiceManager.roleCoin.Init.bind(this.#ServiceManager.roleCoin), this.#ServiceManager.roleBuilding.AddBuildingInfo.bind(this.#ServiceManager.roleBuilding)] },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true, IsInvalid: this.#ServiceManager.roleBuilding.CheckContainsBuilding.bind(this.#ServiceManager.roleBuilding, 2) },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "dev.devAddCoin", Params: { "Num": 9999999 }, Describe: '增加资源', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "dev.devAddCoin", Params: { "Num": 9999999 }, Describe: '增加资源', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "dev.devAddCoin", Params: { "Num": 9999999 }, Describe: '增加资源', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守加速完成', Immediate: true },
    { Cmd: "dev.devAddCoin", Params: { "Num": 9999999 }, Describe: '增加资源', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守加速完成', Immediate: true },
    
    { Cmd: "dev.devAddCoin", Params: { "Num": 9999999 }, Describe: '增加资源', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 1, "TechClassID": 1 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 3, "TechClassID": 1 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 4, "TechClassID": 1 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 6, "TechClassID": 1 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 7, "TechClassID": 1 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "dev.devAddCoin", Params: { "Num": 9999999 }, Describe: '增加资源', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 9, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 10, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 11, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 12, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 13, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "dev.devAddCoin", Params: { "Num": 9999999 }, Describe: '增加资源', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 15, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 16, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "dev.devAddCoin", Params: { "Num": 9999999 }, Describe: '增加资源', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 21, "TechClassID": 3 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 22, "TechClassID": 3 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 23, "TechClassID": 3 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 24, "TechClassID": 3 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 25, "TechClassID": 3 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 26, "TechClassID": 3 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 27, "TechClassID": 3 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 28, "TechClassID": 3 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 29, "TechClassID": 3 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "dev.devAddCoin", Params: { "Num": 9999999 }, Describe: '增加资源', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 30, "TechClassID": 4 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 31, "TechClassID": 4 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 32, "TechClassID": 4 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 33, "TechClassID": 4 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 34, "TechClassID": 4 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
]