// const this.#ServiceManagerManager = require('../app/service_manager');
// /**
//  * @type this.#ServiceManagerManager this.#ServiceManager
//  */
// let this.#ServiceManager;
// -- 以上代码仅为了方便编写脚本命令（取消注释可以使用this.#ServiceManager及链式调用的代码提示，再运行前需要注释掉，否则会导致无法正常运行 --

[
    { Cmd: 'role.getMyRoleInfo', Params: {}, Describe: '获取当前玩家信息', Immediate: true },
    { Cmd: "army.downHero", Params: { "RoleArmyID": this.#ServiceManager.roleArmy.GetRoleArmyID.bind(this.#ServiceManager.roleArmy, 1), "ManagerID": this.#ServiceManager.roleHero.GetRoleHeroID.bind(this.#ServiceManager.roleHero, 340), "SecondID": 0, "ThirdID": 0, "ReReservist": 1 }, Describe: '下阵解散部队', Immediate: true, Handler: this.#ServiceManager.roleArmy.UpdateArmyInfo.bind(this.#ServiceManager.roleArmy) },
    { Cmd: "army.downHero", Params: { "RoleArmyID": this.#ServiceManager.roleArmy.GetRoleArmyID.bind(this.#ServiceManager.roleArmy, 1), "ManagerID": 0, "SecondID": this.#ServiceManager.roleHero.GetRoleHeroID.bind(this.#ServiceManager.roleHero, 323), "ThirdID": 0, "ReReservist": 1 }, Describe: '下阵解散部队', Immediate: true, Handler: this.#ServiceManager.roleArmy.UpdateArmyInfo.bind(this.#ServiceManager.roleArmy) },
    { Cmd: "army.upHero", Params: { "RoleArmyID": this.#ServiceManager.roleArmy.GetRoleArmyID.bind(this.#ServiceManager.roleArmy, 1), "ArmyClass": 1, "Manager": [this.#ServiceManager.roleHero.GetRoleHeroID.bind(this.#ServiceManager.roleHero, 340), 1], "Second": null, "Third": null, "ArmyType": 1 }, Describe: '上阵创建部队', Immediate: true, Handler: this.#ServiceManager.roleArmy.UpdateArmyInfo.bind(this.#ServiceManager.roleArmy) },
    { Cmd: "army.upHero", Params: { "RoleArmyID": this.#ServiceManager.roleArmy.GetRoleArmyID.bind(this.#ServiceManager.roleArmy, 1), "ArmyClass": 1, "Manager": null, "Second": [this.#ServiceManager.roleHero.GetRoleHeroID.bind(this.#ServiceManager.roleHero, 323), 1], "Third": null, "ArmyType": 1 }, Describe: '上阵创建部队', Immediate: true, Handler: this.#ServiceManager.roleArmy.UpdateArmyInfo.bind(this.#ServiceManager.roleArmy) },
    { Cmd: "army.downHero", Params: { "RoleArmyID": this.#ServiceManager.roleArmy.GetRoleArmyID.bind(this.#ServiceManager.roleArmy, 1), "ManagerID": this.#ServiceManager.roleHero.GetRoleHeroID.bind(this.#ServiceManager.roleHero, 340), "SecondID": 0, "ThirdID": 0, "ReReservist": 1 }, Describe: '下阵解散部队', Immediate: true, Handler: this.#ServiceManager.roleArmy.UpdateArmyInfo.bind(this.#ServiceManager.roleArmy) },
    { Cmd: "army.upHero", Params: { "RoleArmyID": this.#ServiceManager.roleArmy.GetRoleArmyID.bind(this.#ServiceManager.roleArmy, 1), "ArmyClass": 1, "Manager": [this.#ServiceManager.roleHero.GetRoleHeroID.bind(this.#ServiceManager.roleHero, 340), 1], "Second": null, "Third": null, "ArmyType": 1 }, Describe: '上阵创建部队', Immediate: true, Handler: this.#ServiceManager.roleArmy.UpdateArmyInfo.bind(this.#ServiceManager.roleArmy) },
    { Cmd: "army.downHero", Params: { "RoleArmyID": this.#ServiceManager.roleArmy.GetRoleArmyID.bind(this.#ServiceManager.roleArmy, 1), "ManagerID": 0, "SecondID": this.#ServiceManager.roleHero.GetRoleHeroID.bind(this.#ServiceManager.roleHero, 323), "ThirdID": 0, "ReReservist": 1 }, Describe: '下阵解散部队', Immediate: true, Handler: this.#ServiceManager.roleArmy.UpdateArmyInfo.bind(this.#ServiceManager.roleArmy) },
    { Cmd: "army.upHero", Params: { "RoleArmyID": this.#ServiceManager.roleArmy.GetRoleArmyID.bind(this.#ServiceManager.roleArmy, 1), "ArmyClass": 1, "Manager": null, "Second": [this.#ServiceManager.roleHero.GetRoleHeroID.bind(this.#ServiceManager.roleHero, 323), 1], "Third": null, "ArmyType": 1 }, Describe: '上阵创建部队', Immediate: true, Handler: this.#ServiceManager.roleArmy.UpdateArmyInfo.bind(this.#ServiceManager.roleArmy) },
    { Cmd: "army.downHero", Params: { "RoleArmyID": this.#ServiceManager.roleArmy.GetRoleArmyID.bind(this.#ServiceManager.roleArmy, 1), "ManagerID": this.#ServiceManager.roleHero.GetRoleHeroID.bind(this.#ServiceManager.roleHero, 340), "SecondID": 0, "ThirdID": 0, "ReReservist": 1 }, Describe: '下阵解散部队', Immediate: true, Handler: this.#ServiceManager.roleArmy.UpdateArmyInfo.bind(this.#ServiceManager.roleArmy) },
    { Cmd: "army.downHero", Params: { "RoleArmyID": this.#ServiceManager.roleArmy.GetRoleArmyID.bind(this.#ServiceManager.roleArmy, 1), "ManagerID": 0, "SecondID": this.#ServiceManager.roleHero.GetRoleHeroID.bind(this.#ServiceManager.roleHero, 323), "ThirdID": 0, "ReReservist": 1 }, Describe: '下阵解散部队', Immediate: true, Handler: this.#ServiceManager.roleArmy.UpdateArmyInfo.bind(this.#ServiceManager.roleArmy) },
    { Cmd: "army.upHero", Params: { "RoleArmyID": this.#ServiceManager.roleArmy.GetRoleArmyID.bind(this.#ServiceManager.roleArmy, 1), "ArmyClass": 1, "Manager": [this.#ServiceManager.roleHero.GetRoleHeroID.bind(this.#ServiceManager.roleHero, 340), 1], "Second": null, "Third": null, "ArmyType": 1 }, Describe: '上阵创建部队', Immediate: true, Handler: this.#ServiceManager.roleArmy.UpdateArmyInfo.bind(this.#ServiceManager.roleArmy) },
    { Cmd: "army.upHero", Params: { "RoleArmyID": this.#ServiceManager.roleArmy.GetRoleArmyID.bind(this.#ServiceManager.roleArmy, 1), "ArmyClass": 1, "Manager": null, "Second": [this.#ServiceManager.roleHero.GetRoleHeroID.bind(this.#ServiceManager.roleHero, 323), 1], "Third": null, "ArmyType": 1 }, Describe: '上阵创建部队', Immediate: true, Handler: this.#ServiceManager.roleArmy.UpdateArmyInfo.bind(this.#ServiceManager.roleArmy) },
    { Cmd: "army.downHero", Params: { "RoleArmyID": this.#ServiceManager.roleArmy.GetRoleArmyID.bind(this.#ServiceManager.roleArmy, 1), "ManagerID": this.#ServiceManager.roleHero.GetRoleHeroID.bind(this.#ServiceManager.roleHero, 340), "SecondID": 0, "ThirdID": 0, "ReReservist": 1 }, Describe: '下阵解散部队', Immediate: true, Handler: this.#ServiceManager.roleArmy.UpdateArmyInfo.bind(this.#ServiceManager.roleArmy) },
    { Cmd: "army.upHero", Params: { "RoleArmyID": this.#ServiceManager.roleArmy.GetRoleArmyID.bind(this.#ServiceManager.roleArmy, 1), "ArmyClass": 1, "Manager": [this.#ServiceManager.roleHero.GetRoleHeroID.bind(this.#ServiceManager.roleHero, 340), 1], "Second": null, "Third": null, "ArmyType": 1 }, Describe: '上阵创建部队', Immediate: true, Handler: this.#ServiceManager.roleArmy.UpdateArmyInfo.bind(this.#ServiceManager.roleArmy) },
    { Cmd: "army.downHero", Params: { "RoleArmyID": this.#ServiceManager.roleArmy.GetRoleArmyID.bind(this.#ServiceManager.roleArmy, 1), "ManagerID": 0, "SecondID": this.#ServiceManager.roleHero.GetRoleHeroID.bind(this.#ServiceManager.roleHero, 323), "ThirdID": 0, "ReReservist": 1 }, Describe: '下阵解散部队', Immediate: true, Handler: this.#ServiceManager.roleArmy.UpdateArmyInfo.bind(this.#ServiceManager.roleArmy) },
    { Cmd: "army.upHero", Params: { "RoleArmyID": this.#ServiceManager.roleArmy.GetRoleArmyID.bind(this.#ServiceManager.roleArmy, 1), "ArmyClass": 1, "Manager": null, "Second": [this.#ServiceManager.roleHero.GetRoleHeroID.bind(this.#ServiceManager.roleHero, 323), 1], "Third": null, "ArmyType": 1 }, Describe: '上阵创建部队', Immediate: true, Handler: this.#ServiceManager.roleArmy.UpdateArmyInfo.bind(this.#ServiceManager.roleArmy) },
    { Cmd: "dev.devConscript", "Params": { "Soldiers": 9999999 }, Describe: '补兵', Immediate: true },
    { Cmd: "army.assignSoldiers", Params: { "RoleArmyID": this.#ServiceManager.roleArmy.GetRoleArmyID.bind(this.#ServiceManager.roleArmy, 1), "ManagerNum": 0, "SecondNum": 0, "ThirdNum": 0 }, Describe: '补兵', Immediate: true, Handler: [this.#ServiceManager.roleCity.UpdateCityInfo.bind(this.#ServiceManager.roleCity), this.#ServiceManager.roleHero.UpdateHeroInfo.bind(this.#ServiceManager.roleHero)] },
]