// const this.#ServiceManagerManager = require('../app/service_manager');
// /**
//  * @type this.#ServiceManagerManager this.#ServiceManager
//  */
// let this.#ServiceManager;
// -- 以上代码仅为了方便编写脚本命令（取消注释可以使用this.#ServiceManager及链式调用的代码提示，再运行前需要注释掉，否则会导致无法正常运行 --

[
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "dev.devAddCoin", Params: { "Num": 9999999 }, Describe: '增加资源', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "dev.devAddCoin", Params: { "Num": 9999999 }, Describe: '增加资源', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 2) }, Describe: '升级仓库加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守加速完成', Immediate: true },
    { Cmd: "dev.devAddCoin", Params: { "Num": 9999999 }, Describe: '增加资源', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 1) }, Describe: '升级天守加速完成', Immediate: true },
    { Cmd: "roleBuilding.createBuild", Params: { "BuildingID": 4, "SerialNum": 0, "Pos": 0 }, Describe: '建造兵舍', Immediate: true, Handler: [this.#ServiceManager.roleCoin.Init.bind(this.#ServiceManager.roleCoin), this.#ServiceManager.roleBuilding.AddBuildingInfo.bind(this.#ServiceManager.roleBuilding)] },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍加速完成', Immediate: true },
    { Cmd: "roleBuilding.upLevel", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍', Immediate: true },
    { Cmd: "roleBuilding.upLevelAcc", Params: { "RoleBuildingID": this.#ServiceManager.roleBuilding.GetRoleBuildingID.bind(this.#ServiceManager.roleBuilding, 4) }, Describe: '升级兵舍加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 9, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 9, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 9, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 9, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 9, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 9, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 9, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 9, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 9, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 9, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 12, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 12, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 12, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 12, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 12, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 12, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 12, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 12, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 12, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 12, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 13, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 13, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 13, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 13, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 13, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "dev.devAddCoin", Params: { "Num": 9999999 }, Describe: '增加资源', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 14, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 15, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 15, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 15, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 16, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 16, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 16, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 16, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "dev.devAddCoin", Params: { "Num": 9999999 }, Describe: '增加资源', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 16, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 10, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 10, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 10, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 10, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 10, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 10, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 10, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 10, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 10, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 10, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 11, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 11, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 11, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 11, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 11, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 11, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 11, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 11, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 11, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "roleTech.upLevel", Params: { "TechID": 11, "TechClassID": 2 }, Describe: '升级科技', Immediate: true },
    { Cmd: "roleTech.upLevelAcc", Params: {}, Describe: '升级科技加速完成', Immediate: true },
    { Cmd: "dev.devUnlockFog", Params: {}, Describe: '指定玩家解锁所有迷雾', Immediate: true },
    { Cmd: "dev.devAddCoin", Params: { "Type": "Renown", "Num": "30000" }, Describe: '增加资源', Immediate: true },
    { Cmd: "roleCoin.drawCert", Params: {}, Describe: "购买一次命令书", Immediate: true },
    { Cmd: "roleCoin.drawCert", Params: {}, Describe: "购买一次命令书", Immediate: true },
    { Cmd: "roleCoin.drawCert", Params: {}, Describe: "购买一次命令书", Immediate: true },
]